on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "cddaa081-05d9-479d-8db1-9a61ca114652"
      ARM_CLIENT_SECRET: "olZ7Q~ShO5OwScek3lD2jdnySLUHZo5OhyjVX"
      ARM_SUBSCRIPTION_ID: "5a0855b9-426d-429e-83a9-ea7c4796e9a4"
      ARM_TENANT_ID: "b4379ba6-6d53-47fe-b814-910057a92b2b"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Run Pester tests (pwsh)
        run: |
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
          Invoke-Pester -Path "./tests"
        shell: pwsh
